[workspace]

default-members = ["client"]
members = [
    "client",
    "sonarr_api"
]
resolver = "2"

[workspace.dependencies]
log = "0.4.22"
sonarr_api = {path = "sonarr_api" }
tokio = { version = "1.41.1", features = ["full"] }
